/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_dlgAbout (void)
{
  GtkWidget *dlgAbout;
  GtkWidget *dialog_vbox1;
  GtkWidget *label_about;
  GtkWidget *dialog_action_area1;
  GtkWidget *button_about_close;

  dlgAbout = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (dlgAbout), "dlgAbout", dlgAbout);
  gtk_window_set_title (GTK_WINDOW (dlgAbout), "about: xmms/CD/cover");
  GTK_WINDOW (dlgAbout)->type = GTK_WINDOW_TOPLEVEL;
  gtk_window_set_type_hint(GTK_WINDOW (dlgAbout), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_position (GTK_WINDOW (dlgAbout), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (dlgAbout), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (dlgAbout)->vbox;
  gtk_object_set_data (GTK_OBJECT (dlgAbout), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label_about = gtk_label_new ("\nxmms/CD/cover\n\nxmms-Plugin, Version <ver>\n\nBy\nMagnus Schmidt\n\neMail: xmms@27b-6.de\n      URL: http://ducts.27b-6.de/cdcover      \n");
  gtk_widget_ref (label_about);
  gtk_object_set_data_full (GTK_OBJECT (dlgAbout), "label_about", label_about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_about);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label_about, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dlgAbout)->action_area;
  gtk_object_set_data (GTK_OBJECT (dlgAbout), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  button_about_close = gtk_button_new_with_label ("   OK   ");
  gtk_widget_ref (button_about_close);
  gtk_object_set_data_full (GTK_OBJECT (dlgAbout), "button_about_close", button_about_close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_about_close);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), button_about_close, TRUE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button_about_close, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (dlgAbout), "delete_event",
                      GTK_SIGNAL_FUNC (on_dlgAbout_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (label_about), "realize",
                      GTK_SIGNAL_FUNC (on_label_about_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_about_close), "clicked",
                      GTK_SIGNAL_FUNC (on_button_aboutclosed_clicked),
                      NULL);

  gtk_widget_grab_default (button_about_close);
  return dlgAbout;
}

GtkWidget*
create_dlgConfig (void)
{
  GtkWidget *dlgConfig;
  GtkWidget *vbox_dialog;
  GtkWidget *notebook_general_config;
  GtkWidget *vbox_options;
  GtkWidget *frame_general_options;
  GtkWidget *vbox_general_options;
  GtkWidget *check_last_winpos;
  GtkWidget *check_aspectratio;
  GtkWidget *frame_extensions;
  GtkWidget *extensions_options;
  GtkWidget *extensions_add_box;
  GtkWidget *entry_extension;
  GtkWidget *button_e_add;
  GtkWidget *extensions_hseparator;
  GtkWidget *extensions_list;
  GtkWidget *extensions_scrolledwindow;
  GtkWidget *clist_extensions;
  GtkWidget *label3;
  GtkWidget *vbox3;
  GtkWidget *button_e_up;
  GtkWidget *button_e_down;
  GtkWidget *button_e_delete;
  GtkWidget *frame_searchpaths;
  GtkWidget *vbox_searchpath_options;
  GtkWidget *hbox_addsearchpath;
  GtkWidget *entry_searchpath;
  GtkWidget *button_add;
  GtkWidget *hseparator_searchpath1;
  GtkWidget *hbox_listsearchpaths;
  GtkWidget *searchpath_scrolledwindow;
  GtkWidget *clist_searchpaths;
  GtkWidget *vbox_searchpath_buttons;
  GtkWidget *button_up;
  GtkWidget *button_down;
  GtkWidget *button_delete;
  GtkWidget *button_help;
  GtkWidget *hseparator_searchpath2;
  GtkWidget *vbox_help;
  GtkWidget *hbox_help_header;
  GtkWidget *label_help_header;
  GtkWidget *hbox_help_vars;
  GtkWidget *label_help_vars;
  GtkWidget *label_help_desc;
  GtkWidget *label_notebook_general;
  GtkWidget *vbox1;
  GtkWidget *hbox_skin_selectskin;
  GtkWidget *label_skins_selectskin;
  GtkWidget *scrolledwindow_skins;
  GtkWidget *clist_skins;
  GtkWidget *hseparator_skins1;
  GtkWidget *frame_skin_author;
  GtkWidget *hbox_author;
  GtkWidget *label_skin_author;
  GtkWidget *label_notebook_skins;
  GtkWidget *vbox_actionarea;
  GtkWidget *hbox_actionarea;
  GtkWidget *button_ok;
  GtkWidget *button_cancel;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  dlgConfig = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (dlgConfig), "dlgConfig", dlgConfig);
  gtk_window_set_title (GTK_WINDOW (dlgConfig), "Configuration xmms/CD/cover");
  GTK_WINDOW (dlgConfig)->type = GTK_WINDOW_TOPLEVEL;
  gtk_window_set_type_hint (GTK_WINDOW (dlgConfig), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_position (GTK_WINDOW (dlgConfig), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (dlgConfig), TRUE, TRUE, FALSE);

  vbox_dialog = GTK_DIALOG (dlgConfig)->vbox;
  gtk_object_set_data (GTK_OBJECT (dlgConfig), "vbox_dialog", vbox_dialog);
  gtk_widget_show (vbox_dialog);

  notebook_general_config = gtk_notebook_new ();
  gtk_widget_ref (notebook_general_config);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "notebook_general_config", notebook_general_config,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook_general_config);
  gtk_box_pack_start (GTK_BOX (vbox_dialog), notebook_general_config, TRUE, TRUE, 0);

  vbox_options = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_options);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox_options", vbox_options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_options);
  gtk_container_add (GTK_CONTAINER (notebook_general_config), vbox_options);

  frame_general_options = gtk_frame_new ("General options");
  gtk_widget_ref (frame_general_options);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "frame_general_options", frame_general_options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_general_options);
  gtk_box_pack_start (GTK_BOX (vbox_options), frame_general_options, FALSE, TRUE, 0);

  vbox_general_options = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_general_options);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox_general_options", vbox_general_options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_general_options);
  gtk_container_add (GTK_CONTAINER (frame_general_options), vbox_general_options);

  check_last_winpos = gtk_check_button_new_with_label ("Remember last window position");
  gtk_widget_ref (check_last_winpos);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "check_last_winpos", check_last_winpos,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_last_winpos);
  gtk_box_pack_start (GTK_BOX (vbox_general_options), check_last_winpos, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_last_winpos), 3);
  gtk_tooltips_set_tip (tooltips, check_last_winpos, "Remember the last position of the cover window during different sessions of xmms", NULL);

  check_aspectratio = gtk_check_button_new_with_label ("Preserve aspect ratio");
  gtk_widget_ref (check_aspectratio);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "check_aspectratio", check_aspectratio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_aspectratio);
  gtk_box_pack_start (GTK_BOX (vbox_general_options), check_aspectratio, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_aspectratio), 3);
  gtk_tooltips_set_tip (tooltips, check_aspectratio, "Preserves the aspect ratio of the loaded imaged, so it is not distorted", NULL);

  frame_extensions = gtk_frame_new ("Extensions");
  gtk_widget_ref (frame_extensions);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "frame_extensions", frame_extensions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_extensions);
  gtk_box_pack_start (GTK_BOX (vbox_options), frame_extensions, TRUE, TRUE, 0);

  extensions_options = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (extensions_options);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "extensions_options", extensions_options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (extensions_options);
  gtk_container_add (GTK_CONTAINER (frame_extensions), extensions_options);

  extensions_add_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (extensions_add_box);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "extensions_add_box", extensions_add_box,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (extensions_add_box);
  gtk_box_pack_start (GTK_BOX (extensions_options), extensions_add_box, FALSE, TRUE, 3);
  gtk_container_set_border_width (GTK_CONTAINER (extensions_add_box), 3);

  entry_extension = gtk_entry_new ();
  gtk_widget_ref (entry_extension);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "entry_extension", entry_extension,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_extension);
  gtk_box_pack_start (GTK_BOX (extensions_add_box), entry_extension, TRUE, TRUE, 0);

  button_e_add = gtk_button_new_with_label ("   Add Ext   ");
  gtk_widget_ref (button_e_add);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_e_add", button_e_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_e_add);
  gtk_box_pack_start (GTK_BOX (extensions_add_box), button_e_add, FALSE, FALSE, 3);
  gtk_widget_set_usize (button_e_add, 82, -2);

  extensions_hseparator = gtk_hseparator_new ();
  gtk_widget_ref (extensions_hseparator);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "extensions_hseparator", extensions_hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (extensions_hseparator);
  gtk_box_pack_start (GTK_BOX (extensions_options), extensions_hseparator, FALSE, TRUE, 0);

  extensions_list = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (extensions_list);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "extensions_list", extensions_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (extensions_list);
  gtk_box_pack_start (GTK_BOX (extensions_options), extensions_list, TRUE, TRUE, 3);

  extensions_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (extensions_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "extensions_scrolledwindow", extensions_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (extensions_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (extensions_list), extensions_scrolledwindow, TRUE, TRUE, 3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (extensions_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist_extensions = gtk_clist_new (1);
  gtk_widget_ref (clist_extensions);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "clist_extensions", clist_extensions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist_extensions);
  gtk_container_add (GTK_CONTAINER (extensions_scrolledwindow), clist_extensions);
  gtk_widget_set_usize (clist_extensions, 300, -2);
  gtk_clist_set_column_width (GTK_CLIST (clist_extensions), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist_extensions));

  label3 = gtk_label_new ("label3");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (clist_extensions), 0, label3);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (extensions_list), vbox3, TRUE, TRUE, 3);

  button_e_up = gtk_button_new_with_label ("   Up   ");
  gtk_widget_ref (button_e_up);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_e_up", button_e_up,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_e_up);
  gtk_box_pack_start (GTK_BOX (vbox3), button_e_up, FALSE, FALSE, 3);

  button_e_down = gtk_button_new_with_label ("   Down   ");
  gtk_widget_ref (button_e_down);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_e_down", button_e_down,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_e_down);
  gtk_box_pack_start (GTK_BOX (vbox3), button_e_down, FALSE, FALSE, 3);

  button_e_delete = gtk_button_new_with_label ("   Delete   ");
  gtk_widget_ref (button_e_delete);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_e_delete", button_e_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_e_delete);
  gtk_box_pack_start (GTK_BOX (vbox3), button_e_delete, FALSE, FALSE, 3);

  frame_searchpaths = gtk_frame_new ("Search paths");
  gtk_widget_ref (frame_searchpaths);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "frame_searchpaths", frame_searchpaths,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_searchpaths);
  gtk_box_pack_start (GTK_BOX (vbox_options), frame_searchpaths, TRUE, TRUE, 0);

  vbox_searchpath_options = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_searchpath_options);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox_searchpath_options", vbox_searchpath_options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_searchpath_options);
  gtk_container_add (GTK_CONTAINER (frame_searchpaths), vbox_searchpath_options);

  hbox_addsearchpath = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_addsearchpath);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_addsearchpath", hbox_addsearchpath,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_addsearchpath);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_options), hbox_addsearchpath, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox_addsearchpath), 3);

  entry_searchpath = gtk_entry_new ();
  gtk_widget_ref (entry_searchpath);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "entry_searchpath", entry_searchpath,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_searchpath);
  gtk_box_pack_start (GTK_BOX (hbox_addsearchpath), entry_searchpath, TRUE, TRUE, 3);
  gtk_tooltips_set_tip (tooltips, entry_searchpath, "Enter a new search path, and press \"Add Path\" to add", NULL);

  button_add = gtk_button_new_with_label ("   Add Path   ");
  gtk_widget_ref (button_add);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_add", button_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_add);
  gtk_box_pack_start (GTK_BOX (hbox_addsearchpath), button_add, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, button_add, "Add the path in entry on the left to the search path list", NULL);

  hseparator_searchpath1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator_searchpath1);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hseparator_searchpath1", hseparator_searchpath1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator_searchpath1);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_options), hseparator_searchpath1, FALSE, TRUE, 0);

  hbox_listsearchpaths = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_listsearchpaths);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_listsearchpaths", hbox_listsearchpaths,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_listsearchpaths);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_options), hbox_listsearchpaths, TRUE, TRUE, 3);

  searchpath_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (searchpath_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "searchpath_scrolledwindow", searchpath_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (searchpath_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (hbox_listsearchpaths), searchpath_scrolledwindow, TRUE, TRUE, 3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (searchpath_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist_searchpaths = gtk_clist_new (1);
  gtk_widget_ref (clist_searchpaths);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "clist_searchpaths", clist_searchpaths,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist_searchpaths);
  gtk_container_add (GTK_CONTAINER (searchpath_scrolledwindow), clist_searchpaths);
  gtk_widget_set_usize (clist_searchpaths, 300, -2);
  gtk_tooltips_set_tip (tooltips, clist_searchpaths, "The different path-definitions, where a picture is search for.", NULL);
  gtk_clist_set_column_width (GTK_CLIST (clist_searchpaths), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist_searchpaths));

  vbox_searchpath_buttons = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_searchpath_buttons);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox_searchpath_buttons", vbox_searchpath_buttons,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_searchpath_buttons);
  gtk_box_pack_start (GTK_BOX (hbox_listsearchpaths), vbox_searchpath_buttons, FALSE, TRUE, 3);

  button_up = gtk_button_new_with_label ("   Up   ");
  gtk_widget_ref (button_up);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_up", button_up,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_up);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_buttons), button_up, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, button_up, "Move the selected search path one position up", NULL);

  button_down = gtk_button_new_with_label ("   Down   ");
  gtk_widget_ref (button_down);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_down", button_down,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_down);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_buttons), button_down, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, button_down, "Move the selected search path one position down", NULL);

  button_delete = gtk_button_new_with_label ("   Delete   ");
  gtk_widget_ref (button_delete);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_delete", button_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_delete);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_buttons), button_delete, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, button_delete, "Delete the selected search path", NULL);

  button_help = gtk_button_new_with_label ("   Help   ");
  gtk_widget_ref (button_help);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_help", button_help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_help);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_buttons), button_help, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, button_help, "Help on path definitions", NULL);

  hseparator_searchpath2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator_searchpath2);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hseparator_searchpath2", hseparator_searchpath2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator_searchpath2);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_options), hseparator_searchpath2, FALSE, TRUE, 0);

  vbox_help = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_help);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox_help", vbox_help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (vbox_searchpath_options), vbox_help, FALSE, FALSE, 3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox_help), 4);

  hbox_help_header = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_help_header);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_help_header", hbox_help_header,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_help_header);
  gtk_box_pack_start (GTK_BOX (vbox_help), hbox_help_header, FALSE, FALSE, 0);

  label_help_header = gtk_label_new ("Following variables can be used in the search paths:");
  gtk_widget_ref (label_help_header);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_help_header", label_help_header,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_help_header);
  gtk_box_pack_start (GTK_BOX (hbox_help_header), label_help_header, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_help_header), GTK_JUSTIFY_LEFT);

  hbox_help_vars = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_help_vars);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_help_vars", hbox_help_vars,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_help_vars);
  gtk_box_pack_start (GTK_BOX (vbox_help), hbox_help_vars, TRUE, TRUE, 0);

  label_help_vars = gtk_label_new ("?FILENAME?    \n?FILENAME-EXT?    \n?PATH?    \n?BASENAME?\n*    ");
  gtk_widget_ref (label_help_vars);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_help_vars", label_help_vars,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_help_vars);
  gtk_box_pack_start (GTK_BOX (hbox_help_vars), label_help_vars, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_help_vars), GTK_JUSTIFY_LEFT);

  label_help_desc = gtk_label_new ("Filename without extension\nFilename with extension\nThe complete path to the file\nThe directoryname of the file\nWildcard (only in filename)");
  gtk_widget_ref (label_help_desc);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_help_desc", label_help_desc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_help_desc);
  gtk_box_pack_start (GTK_BOX (hbox_help_vars), label_help_desc, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_help_desc), GTK_JUSTIFY_LEFT);

  label_notebook_general = gtk_label_new ("General");
  gtk_widget_ref (label_notebook_general);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_notebook_general", label_notebook_general,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_notebook_general);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_general_config), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_general_config), 0), label_notebook_general);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook_general_config), vbox1);

  hbox_skin_selectskin = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_skin_selectskin);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_skin_selectskin", hbox_skin_selectskin,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_skin_selectskin);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox_skin_selectskin, FALSE, FALSE, 0);

  label_skins_selectskin = gtk_label_new ("Select a skin:");
  gtk_widget_ref (label_skins_selectskin);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_skins_selectskin", label_skins_selectskin,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_skins_selectskin);
  gtk_box_pack_start (GTK_BOX (hbox_skin_selectskin), label_skins_selectskin, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_skins_selectskin), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label_skins_selectskin), 3, 3);

  scrolledwindow_skins = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow_skins);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "scrolledwindow_skins", scrolledwindow_skins,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow_skins);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow_skins, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_skins), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist_skins = gtk_clist_new (3);
  gtk_widget_ref (clist_skins);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "clist_skins", clist_skins,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist_skins);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_skins), clist_skins);
  gtk_container_set_border_width (GTK_CONTAINER (clist_skins), 3);
  gtk_tooltips_set_tip (tooltips, clist_skins, "Select a skin", NULL);
  gtk_clist_set_column_width (GTK_CLIST (clist_skins), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_skins), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_skins), 2, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist_skins));

  hseparator_skins1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator_skins1);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hseparator_skins1", hseparator_skins1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator_skins1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator_skins1, FALSE, TRUE, 0);

  frame_skin_author = gtk_frame_new ("Skin author:");
  gtk_widget_ref (frame_skin_author);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "frame_skin_author", frame_skin_author,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_skin_author);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_skin_author, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_skin_author), 3);

  hbox_author = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_author);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_author", hbox_author,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_author);
  gtk_container_add (GTK_CONTAINER (frame_skin_author), hbox_author);

  label_skin_author = gtk_label_new (" ");
  gtk_widget_ref (label_skin_author);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_skin_author", label_skin_author,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_skin_author);
  gtk_box_pack_start (GTK_BOX (hbox_author), label_skin_author, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label_skin_author), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_skin_author), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_skin_author), 4, 0);

  label_notebook_skins = gtk_label_new ("Skins");
  gtk_widget_ref (label_notebook_skins);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "label_notebook_skins", label_notebook_skins,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_notebook_skins);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_general_config), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_general_config), 1), label_notebook_skins);

  vbox_actionarea = GTK_DIALOG (dlgConfig)->action_area;
  gtk_object_set_data (GTK_OBJECT (dlgConfig), "vbox_actionarea", vbox_actionarea);
  gtk_widget_show (vbox_actionarea);
  gtk_container_set_border_width (GTK_CONTAINER (vbox_actionarea), 10);

  hbox_actionarea = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox_actionarea);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "hbox_actionarea", hbox_actionarea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_actionarea);
  gtk_box_pack_start (GTK_BOX (vbox_actionarea), hbox_actionarea, TRUE, TRUE, 0);

  button_ok = gtk_button_new_with_label ("   OK   ");
  gtk_widget_ref (button_ok);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_ok", button_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_ok);
  gtk_box_pack_start (GTK_BOX (hbox_actionarea), button_ok, FALSE, FALSE, 0);

  button_cancel = gtk_button_new_with_label ("   Cancel   ");
  gtk_widget_ref (button_cancel);
  gtk_object_set_data_full (GTK_OBJECT (dlgConfig), "button_cancel", button_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (hbox_actionarea), button_cancel, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (dlgConfig), "delete_event",
                      GTK_SIGNAL_FUNC (on_dlgConfig_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dlgConfig), "realize",
                      GTK_SIGNAL_FUNC (on_dlgConfig_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (check_aspectratio), "toggled",
                      GTK_SIGNAL_FUNC (on_dlgConfig_check_aspectratio_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_e_add), "clicked",
                      GTK_SIGNAL_FUNC (on_button_e_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist_extensions), "select_row",
                      GTK_SIGNAL_FUNC (on_clist_extensions_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_e_up), "clicked",
                      GTK_SIGNAL_FUNC (on_button_e_up_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_e_down), "clicked",
                      GTK_SIGNAL_FUNC (on_button_e_down_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_e_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_button_e_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_add), "clicked",
                      GTK_SIGNAL_FUNC (on_button_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist_searchpaths), "select_row",
                      GTK_SIGNAL_FUNC (on_clist_searchpaths_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_up), "clicked",
                      GTK_SIGNAL_FUNC (on_button_up_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_down), "clicked",
                      GTK_SIGNAL_FUNC (on_dglConfig_button_down_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_dglConfig_button_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_help), "clicked",
                      GTK_SIGNAL_FUNC (on_dlgConfig_button_help_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist_skins), "select_row",
                      GTK_SIGNAL_FUNC (on_dlgConfig_clist_skins_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_dlgConfig_button_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_dlgConfig_button_cancel_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (dlgConfig), "tooltips", tooltips);

  return dlgConfig;
}

